### ISSUE TITLE
Raspberry pi ARM compilation

### ISSUE THREAD

**Issue by hvdwolf** [OT-dm/7870pwd_extract#2]
It compiles fine on my x86_64 .

On my raspberry pi 4  running Debian Bookworm (Linux RPi4 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux), I needed to add a include <memory> into passwd_extract.cpp

```
diff --git a/passwd_extract.cpp b/passwd_extract.cpp
index e61e5d9..532cfcb 100644
--- a/passwd_extract.cpp
+++ b/passwd_extract.cpp
@@ -6,6 +6,7 @@
 #include <cstdio>
 #include <cstring>
 #include <algorithm>
+#include <memory>
 #include <minizip/unzip.h>
 #include <openssl/conf.h>
 #include <openssl/evp.h>
```

I did not create a pull request as I do not know what you want to do with it.

Edit: The RPi4 version works fine as well. I already tried it on a 7870 firmware (MKD 7870_UI2_2000x1200_国外付费语音_20240124_lzp.zip)

**Comment by OT-dm** [comment]
The proposed change committed. Thx!
